issuer_uri: http://localhost:8080/realms/org-apae
jwk_set_uri: http://localhost:8080/realms/org-apae/protocol/openid-connect/certs

spring:
  application:
    name: documentos-escolares
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer_uri}
          jwk_set_uri: ${jwk_set_uri}

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

client:
  storage:
    endpoint:
      url: http://localhost:8081/bucket

server:
  port: 8082