realms_name: master
issuer_uri: http://localhost:8080/realms/${realms_name}
jwk_set_uri: http://localhost:8080/realms/${realms_name}/protocol/openid-connect/certs

spring:
  application:
    name: documentos-digitalizados
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer_uri}
          jwk_set_uri: ${jwk_set_uri}
  mvc:
    dispatch-options-request: true

minio:
  endpoint: http://localhost:9001
  accessKey: minioadmin
  secretKey: minioadmin

server:
  port: 8081
