spring.datasource.url=jdbc:postgresql://localhost:5200/apae
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=profissional_da_saude

server.port=8081

spring.jackson.deserialization.fail-on-unknown-properties=false