name: apae

services:
  db:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER:-apae-postgres}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - apae-postgres-data:/var/lib/postgresql/data
    networks:
      - apae-network
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    container_name: minio_docs_apae
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - apae-minio-data:/data
    user: root
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    networks:
      - apae-network
    restart: unless-stopped


volumes:
  apae-postgres-data:
  apae-minio-data:

networks:
  apae-network:
    driver: bridge