spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5200/apae
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

  mvc:
    servlet:
      path: /api

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

app:
  token:
    secret: "U29tZVNlY3JldEF0TGVhc3QtMjU2Qml0cw=="

minio:
  access:
    key: "ROOTUSER"
    secret: "CHANGEME123"
  url: "http://127.0.0.1:9000"

server:
  port: 8090