name: apae

services:
  db:
    image: postgres:15
    container_name: apae-pg
    environment:
      POSTGRES_DB: apae
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5200:5432"
    volumes:
      - apae-pg-data:/var/lib/postgresql/data
    networks:
      - apae-network
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    container_name: minio_docs_apae
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    volumes:
      - ${HOME}/minio/data:/data
    user: "${UID}:${GID}"
    command: server /data --console-address ":9001"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    
volumes:
  apae-pg-data:

networks:
  apae-network:
    driver: bridge
