spring.application.name=api-crud-pacientes

# Banco de dados
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#issuer_uri: http://localhost:8080/realms/master
#jwk_set_uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

#spring.security.oauth2.resourceserver.jwt.issuer-uri=${issuer_uri}
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${jwk_set_uri}

server.port=8086

documento.digitalizado.url: http://localhost:8081/api/documents