sonar.projectKey=apae-geral-frontend
sonar.projectName=apae-geral-frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/.next/**, public/**, **/next-env.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8