import type { Metadata } from "next";
import { Geist, Geist_Mono, Baloo_2, Nunito } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/ToastProvider";

export const baloo2 = Baloo_2({
  subsets: ["latin"],
  weight: ["700"], // bold
  variable: "--font-baloo2"
});

export const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600"], // regular e semi-bold
  variable: "--font-nunito"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "APAE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
