spring.application.name=documentos-pessoais-digitalizados


#Url Base do serviço de criação de bucket
storage.service.base.url=""

# Diretório onde serão salvos os arquivos no bucket
minio.folder.name=documentos-pessoais

#Configs Minio
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin

#Dominio da aplicação
app.web.domain=http://localhost:8080

#Configs upload de arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
