# application-dev.properties
spring.datasource.url=jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

minio.folder.name=documentos-pessoais

storage.service.base.url=""
minio.endpoint=http://localhost:9000
minio.access-key=default
minio.secret-key=secret123

app.web.domain=http://localhost:8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB