server:
  port: 9000

realms_name: master
url_login_token: http://localhost:8080/realms/${realms_name}/protocol/openid-connect/token
client_id: client-apae
client_secret: 4zp5s4iuBv6SboJPhbBPwK9s1SdvIOux
issuer_uri: http://localhost:8080/realms/${realms_name}
keycloak_admin_url: http://localhost:8080/admin/realms/${realms_name}
default_role: admin

spring:
  application:
    name: auth
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${client_id}
            client-secret: ${client_secret}
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: ${issuer_uri}
      resourceserver:
        jwt:
          issuer-uri: ${issuer_uri}
