server:
  port: 8085

url_login_token: http://localhost:8080/realms/org-apae/protocol/openid-connect/token
client_id: client-apae
client_secret: 18p6F64hHrSjxjTrzCElglkFiF1j5Bho
issuer_uri: http://localhost:8080/realms/org-apae

spring:
  application:
    name: auth
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${client_id}
            client-secret: ${client_secret}
            scope:
              - openid
        provider:
          keycloak:
              issuer-uri: ${issuer_uri}
      resourceserver:
        jwt:
          issuer-uri: ${issuer_uri}
