spring.application.name=documentos-pessoais-digitalizados

minio.endpoint=http://localhost:9000

client.storage.endpoint.url=http://localhost:8081/bucket

minio.access-key=minioadmin
minio.secret-key=minioadmin

minio.folder.name=documentos-pessoais
minio.expiration.time=2

#Configs upload de arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
