spring.application.name=documentos-medicos-digitalizados

minio.url=http://localhost:9000

client.storage.endpoint.url=http://localhost:8081/bucket

minio.access-key=minioadmin
minio.secret-key=minioadmin

issuer_uri: http://localhost:8080/realms/org-apae
jwk_set_uri: http://localhost:8080/realms/org-apae/protocol/openid-connect/certs

spring.security.oauth2.resourceserver.jwt.issuer-uri=${issuer_uri}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${jwk_set_uri}
server.port=8083
