CREATE SCHEMA IF NOT EXISTS apae_geral;

SET search_path TO apae_geral;

CREATE TABLE usuarios (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    nome_completo VARCHAR(255),
    cargo VARCHAR(255) NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_cpf UNIQUE (cpf),
    CONSTRAINT chk_usuarios_cargo CHECK (cargo IN ('ADMIN', 'USER'))
);

CREATE TABLE password_recovery_token (
    id UUID PRIMARY KEY,
    token_hash VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    used_at TIMESTAMP(6),
    CONSTRAINT uk_password_recovery_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_recovery_token_user
        FOREIGN KEY (user_id) REFERENCES usuarios (id)
        ON UPDATE CASCADE
);

CREATE TABLE enderecos (
    id UUID PRIMARY KEY,
    cidade VARCHAR(255) NOT NULL,
    cep VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    bairro VARCHAR(255) NOT NULL,
    rua VARCHAR(255) NOT NULL,
    numero VARCHAR(255) NOT NULL,
    complemento VARCHAR(255)
);

CREATE TABLE areas_de_atendimento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area VARCHAR(255) NOT NULL,
    CONSTRAINT uk_areas_de_atendimento_area UNIQUE (area)
);

CREATE TABLE profissionais_da_saude (
    id UUID PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    area_de_atendimento VARCHAR(255),
    contato VARCHAR(255) NOT NULL,
    documento_profissional VARCHAR(255),
    rg VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    endereco_id UUID,
    foto_perfil VARCHAR(255),
    CONSTRAINT uk_profissionais_da_saude_email UNIQUE (email),
    CONSTRAINT uk_profissionais_da_saude_documento_profissional UNIQUE (documento_profissional),
    CONSTRAINT uk_profissionais_da_saude_rg UNIQUE (rg),
    CONSTRAINT uk_profissionais_da_saude_endereco UNIQUE (endereco_id),
    CONSTRAINT fk_profissionais_da_saude_area_de_atendimento
        FOREIGN KEY (area_de_atendimento) REFERENCES areas_de_atendimento (area)
        ON UPDATE CASCADE,
    CONSTRAINT fk_profissionais_da_saude_endereco
        FOREIGN KEY (endereco_id) REFERENCES enderecos (id)
        ON UPDATE CASCADE
);

CREATE TABLE disponibilidades (
    id UUID PRIMARY KEY,
    day VARCHAR(255) NOT NULL,
    shift VARCHAR(255) NOT NULL,
    professional_id UUID NOT NULL,
    CONSTRAINT chk_disponibilidades_day
        CHECK (day IN ('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO')),
    CONSTRAINT chk_disponibilidades_shift
        CHECK (shift IN ('MANHA', 'TARDE')),
    CONSTRAINT fk_disponibilidades_profissional
        FOREIGN KEY (professional_id) REFERENCES profissionais_da_saude (id)
        ON UPDATE CASCADE
);

CREATE TABLE pacientes (
    id UUID PRIMARY KEY,
    nome_completo VARCHAR(255) NOT NULL,
    naturalidade VARCHAR(255) NOT NULL,
    data_de_nascimento DATE NOT NULL,
    contato VARCHAR(255) NOT NULL,
    numero_registro_de_nascimento VARCHAR(255) NOT NULL,
    cartorio VARCHAR(255) NOT NULL,
    fls VARCHAR(255) NOT NULL,
    livro VARCHAR(255) NOT NULL,
    rg VARCHAR(255) NOT NULL,
    data_de_emissao DATE NOT NULL,
    orgao_emissor VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    cns VARCHAR(255) NOT NULL,
    nis VARCHAR(255) NOT NULL,
    data_de_cadastro DATE NOT NULL,
    alergias VARCHAR(255) NOT NULL,
    is_aluno BOOLEAN NOT NULL,
    is_apagado BOOLEAN NOT NULL DEFAULT FALSE,
    endereco_id UUID,
    CONSTRAINT uk_pacientes_rg UNIQUE (rg),
    CONSTRAINT uk_pacientes_cpf UNIQUE (cpf),
    CONSTRAINT uk_pacientes_endereco UNIQUE (endereco_id),
    CONSTRAINT fk_pacientes_endereco
        FOREIGN KEY (endereco_id) REFERENCES enderecos (id)
        ON UPDATE CASCADE
);

CREATE TABLE parentes (
    id UUID PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    rg VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    vivo BOOLEAN NOT NULL,
    profissao VARCHAR(255) NOT NULL,
    parentesco VARCHAR(255) NOT NULL,
    paciente_id UUID NOT NULL,
    CONSTRAINT fk_parentes_paciente
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id)
        ON UPDATE CASCADE
);

CREATE TABLE responsaveis (
    id UUID PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    contato VARCHAR(255) NOT NULL,
    parentesco VARCHAR(255) NOT NULL,
    endereco_id UUID,
    paciente_id UUID NOT NULL,
    CONSTRAINT uk_responsaveis_endereco UNIQUE (endereco_id),
    CONSTRAINT fk_responsaveis_endereco
        FOREIGN KEY (endereco_id) REFERENCES enderecos (id)
        ON UPDATE CASCADE,
    CONSTRAINT fk_responsaveis_paciente
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id)
        ON UPDATE CASCADE
);

CREATE TABLE transtornos (
    id UUID PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    CONSTRAINT uk_transtornos_nome UNIQUE (nome)
);

CREATE TABLE vacinas (
    id UUID PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    CONSTRAINT uk_vacinas_nome UNIQUE (nome)
);

CREATE TABLE paciente_vacina (
    paciente_id UUID NOT NULL,
    vacina_id UUID NOT NULL,
    PRIMARY KEY (paciente_id, vacina_id),
    CONSTRAINT fk_paciente_vacina_paciente
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id)
        ON UPDATE CASCADE,
    CONSTRAINT fk_paciente_vacina_vacina
        FOREIGN KEY (vacina_id) REFERENCES vacinas (id)
        ON UPDATE CASCADE
);

CREATE TABLE cadastros_anuais (
    id UUID PRIMARY KEY,
    bpc VARCHAR(255) NOT NULL,
    doencas VARCHAR(255) NOT NULL,
    medicamentos_continuos VARCHAR(255),
    renda_familiar NUMERIC(38, 2) NOT NULL,
    ano INTEGER NOT NULL,
    paciente_id UUID NOT NULL,
    CONSTRAINT uk_cadastros_anuais_paciente_ano UNIQUE (paciente_id, ano),
    CONSTRAINT fk_cadastros_anuais_paciente
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id)
        ON UPDATE CASCADE
);

CREATE TABLE cadastro_anual_transtorno (
    cadastro_anual_id UUID NOT NULL,
    transtorno_id UUID NOT NULL,
    PRIMARY KEY (cadastro_anual_id, transtorno_id),
    CONSTRAINT fk_cadastro_anual_transtorno_cadastro_anual
        FOREIGN KEY (cadastro_anual_id) REFERENCES cadastros_anuais (id)
        ON UPDATE CASCADE,
    CONSTRAINT fk_cadastro_anual_transtorno_transtorno
        FOREIGN KEY (transtorno_id) REFERENCES transtornos (id)
        ON UPDATE CASCADE
);

CREATE TABLE cadastro_anual_areas_de_atendimento (
    cadastro_anual_id UUID NOT NULL,
    areas_de_atendimento_id INTEGER NOT NULL,
    PRIMARY KEY (cadastro_anual_id, areas_de_atendimento_id),
    CONSTRAINT fk_cadastro_anual_area_cadastro_anual
        FOREIGN KEY (cadastro_anual_id) REFERENCES cadastros_anuais (id)
        ON UPDATE CASCADE,
    CONSTRAINT fk_cadastro_anual_area_area_de_atendimento
        FOREIGN KEY (areas_de_atendimento_id) REFERENCES areas_de_atendimento (id)
        ON UPDATE CASCADE
);

CREATE TABLE agendamentos (
    id UUID PRIMARY KEY,
    profissional_id UUID NOT NULL,
    cadastro_anual_id UUID NOT NULL,
    frequencia_dias INTEGER NOT NULL,
    hora TIME(6) NOT NULL,
    data_inicial DATE NOT NULL,
    data_final DATE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMP(6),
    substituido_por_id UUID,
    atualizado_de_id UUID,
    CONSTRAINT fk_agendamentos_profissional
        FOREIGN KEY (profissional_id) REFERENCES profissionais_da_saude (id)
        ON UPDATE CASCADE,
    CONSTRAINT fk_agendamentos_cadastro_anual
        FOREIGN KEY (cadastro_anual_id) REFERENCES cadastros_anuais (id)
        ON UPDATE CASCADE,
    CONSTRAINT fk_agendamentos_substituido_por
        FOREIGN KEY (substituido_por_id) REFERENCES agendamentos (id)
        ON UPDATE CASCADE,
    CONSTRAINT fk_agendamentos_atualizado_de
        FOREIGN KEY (atualizado_de_id) REFERENCES agendamentos (id)
        ON UPDATE CASCADE
);

CREATE TABLE agendamento_gerado (
    id UUID PRIMARY KEY,
    agendamento_id UUID NOT NULL,
    data_hora_agendada TIMESTAMP(6) NOT NULL,
    data_hora_sobrescrita TIMESTAMP(6),
    realizada BOOLEAN NOT NULL DEFAULT FALSE,
    cancelada BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_cancelamento VARCHAR(500),
    paciente_id UUID NOT NULL,
    CONSTRAINT fk_agendamento_gerado_agendamento
        FOREIGN KEY (agendamento_id) REFERENCES agendamentos (id)
        ON UPDATE CASCADE,
    CONSTRAINT fk_agendamento_gerado_paciente
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id)
        ON UPDATE CASCADE
);

CREATE INDEX idx_gerado_agendamento
    ON agendamento_gerado (agendamento_id);

CREATE INDEX idx_gerado_data
    ON agendamento_gerado (data_hora_agendada);

CREATE INDEX idx_gerado_paciente
    ON agendamento_gerado (paciente_id, data_hora_agendada);

CREATE TABLE falta (
    id UUID PRIMARY KEY,
    agendamento_gerado_id UUID NOT NULL,
    data_falta DATE NOT NULL,
    justificativa VARCHAR(500),
    notificado BOOLEAN NOT NULL DEFAULT FALSE,
    is_justificada BOOLEAN NOT NULL DEFAULT FALSE,
    documento_justificativa_id VARCHAR(255),
    CONSTRAINT uk_falta_documento_justificativa UNIQUE (documento_justificativa_id),
    CONSTRAINT fk_falta_agendamento_gerado
        FOREIGN KEY (agendamento_gerado_id) REFERENCES agendamento_gerado (id)
        ON UPDATE CASCADE
);

CREATE INDEX idx_falta_gerado
    ON falta (agendamento_gerado_id);
