spring.application.name=documentos-medicos-digitalizados

client.storage.endpoint.url=http://localhost:8080/bucket
minio.access-key=MsEpAvGOu8TAAjsEdzKg
minio.secret-key=XGCyqxu0qCpF5UGu3DhBOCORJvzfBxi0z6IuHcLb

