import type { Metadata } from "next";
import { Baloo_2, Nunito } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";

const baloo2 = Baloo_2({
  subsets: ["latin"],
});

const nunito = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src="https://vlibras.gov.br/app/vlibras-plugin.js"
        ></script>
      </head>
      <body className={`${nunito.className}`}>
        <Header />
        {children}
        <Footer />
        <div
          dangerouslySetInnerHTML={{
            __html: `
              <div vw class="enabled">
                <div vw-access-button class="active"></div>
                <div vw-plugin-wrapper>
                  <div class="vw-plugin-top-wrapper"></div>
                </div>
              </div>
              <script>
                new window.VLibras.Widget('https://vlibras.gov.br/app');
              </script>
            `,
          }}
        />
      </body>
    </html>
  );
}
