version: '3.8'

services:
  db:
    image: postgres:16.2-alpine # Versão estável e leve do PostgreSQL
    container_name: postgres-apae # Nome do container
    restart: always
    environment:
      POSTGRES_DB: apae           # Deve ser o mesmo nome do seu banco: apae
      POSTGRES_USER: user         # Deve ser o mesmo usuário: user
      POSTGRES_PASSWORD: pass     # Deve ser a mesma senha: pass
    ports:
      - "5200:5432" # Mapeia a porta 5200 do HOST (que você usou no application.yml) para a porta padrão 5432 do container.
    volumes:
      - postgres_data:/var/lib/postgresql/data # Cria um volume para persistir os dados

volumes:
  postgres_data: