name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  setup-docker-compose:
    name: Set up Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verifique a instalação

      - name: Start Docker Compose
        run: docker-compose -f docker/docker-compose.yml up -d

  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    needs: setup-docker-compose

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Wait for DB to be healthy
        run: |
          until [ "$(docker inspect -f '{{ .State.Health.Status }}' demo_database)" = "healthy" ]; do
            echo "Waiting for demo_database to become healthy..."
            sleep 2
          done

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Tests with JUnit
        run: ./gradlew build:test

  build:
    name: Build Spring Boot Project
    runs-on: ubuntu-latest
    needs: setup-docker-compose # Depende do job 'setup-docker-compose'

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Wait for DB to be healthy
        run: |
          until [ "$(docker inspect -f '{{ .State.Health.Status }}' demo_database)" = "healthy" ]; do
            echo "Waiting for demo_database to become healthy..."
            sleep 2
          done

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew demo:build
