name: Docker Build & Publish

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-backend:
    name: Build & publish backend
    uses: IFPBEsp/APAE-INFRA/.github/workflows/docker-build-publish-image.yml@dev
    with:
      context: ./apps/api
      dockerfile: ./apps/api/Dockerfile
      image-name: apae-geral-backend
      platforms: '["linux/amd64"]'
      scan-severity: "HIGH,CRITICAL"

  publish-frontend:
    name: Build & publish frontend
    uses: IFPBEsp/APAE-INFRA/.github/workflows/docker-build-publish-image.yml@dev
    with:
      context: ./apps/apae
      dockerfile: ./apps/apae/Dockerfile
      image-name: apae-geral-frontend
      build-args: |
        NEXT_PUBLIC_API_URL=/apae-geral/api
      platforms: '["linux/amd64"]'
      scan-severity: "HIGH,CRITICAL"