name: SonarQube Analysis

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

permissions:
  contents: read

jobs:
  sonar-backend:
    name: Backend Analysis (Maven)
    uses: IFPBEsp/APAE-INFRA/.github/workflows/reusable-sonarqube-maven.yml@dev
    with:
      project-key: "apae-geral-backend"
      organization: "ifpbesp"
      working-directory: "apps/api"
      java-version: "21"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sonar-frontend:
    name: Frontend Analysis (Node)
    uses: IFPBEsp/APAE-INFRA/.github/workflows/reusable-sonarqube-node.yml@dev
    with:
      project-key: "apae-geral-frontend"
      organization: "ifpbesp"
      working-directory: "apps/apae"
      node-version: "22"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
